version: '2'
services:
  db:
    build: .
    container_name: psql
    volumes:
      - psql-db:/var/lib/postgresql/data
      - ./work:/usr/src
    ports:
      - "5432:5432"
    env_file: .env

volumes:
  psql-db:
    driver: local